### ISSUE TITLE
Import External Classes (Types)

### ISSUE THREAD

**Issue by Sunnatilla** [igorsimko/camunda-script-editor-plugin#1]
It is possible import external classes (Types) ?
For example I have some BaseModel of process, which I want to import for using in task script.

**Comment by igorsimko** [comment]
Hey @Sunnatilla, thank you for your question. I'm not sure if I understand your question correctly, but any extension you can do in [module.js](https://github.com/igorsimko/camunda-script-editor-plugin/blob/master/client/module.js).

**Comment by Sunnatilla** [comment]
Hi @igorsimko, thank you for feedback
